/*
aiproductdataenhancer/service.proto

Testing AiProductDataEnhancerAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aiproductdataenhancer

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Gemini-Commerce/go-client-ai-product-data-enhancer"
)

func Test_aiproductdataenhancer_AiProductDataEnhancerAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AiProductDataEnhancerAPIService AiProductDataEnhancerFillProductData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AiProductDataEnhancerAPI.AiProductDataEnhancerFillProductData(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AiProductDataEnhancerAPIService AiProductDataEnhancerTranslateData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AiProductDataEnhancerAPI.AiProductDataEnhancerTranslateData(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
