/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AiProductDataEnhancerAPI interface {

	/*
	AiProductDataEnhancerFillProductData Method for AiProductDataEnhancerFillProductData

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest
	*/
	AiProductDataEnhancerFillProductData(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest

	// AiProductDataEnhancerFillProductDataExecute executes the request
	//  @return AiproductdataenhancerFillProductDataResponse
	AiProductDataEnhancerFillProductDataExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest) (*AiproductdataenhancerFillProductDataResponse, *http.Response, error)

	/*
	AiProductDataEnhancerFillProductDataCheck Method for AiProductDataEnhancerFillProductDataCheck

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest
	*/
	AiProductDataEnhancerFillProductDataCheck(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest

	// AiProductDataEnhancerFillProductDataCheckExecute executes the request
	//  @return AiproductdataenhancerFillProductDataCheckResponse
	AiProductDataEnhancerFillProductDataCheckExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest) (*AiproductdataenhancerFillProductDataCheckResponse, *http.Response, error)

	/*
	AiProductDataEnhancerTranslateData Method for AiProductDataEnhancerTranslateData

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest
	*/
	AiProductDataEnhancerTranslateData(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest

	// AiProductDataEnhancerTranslateDataExecute executes the request
	//  @return AiproductdataenhancerTranslateDataResponse
	AiProductDataEnhancerTranslateDataExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest) (*AiproductdataenhancerTranslateDataResponse, *http.Response, error)
}

// AiProductDataEnhancerAPIService AiProductDataEnhancerAPI service
type AiProductDataEnhancerAPIService service

type AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest struct {
	ctx context.Context
	ApiService AiProductDataEnhancerAPI
	body *AiproductdataenhancerFillProductDataRequest
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest) Body(body AiproductdataenhancerFillProductDataRequest) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest {
	r.body = &body
	return r
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest) Execute() (*AiproductdataenhancerFillProductDataResponse, *http.Response, error) {
	return r.ApiService.AiProductDataEnhancerFillProductDataExecute(r)
}

/*
AiProductDataEnhancerFillProductData Method for AiProductDataEnhancerFillProductData

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest
*/
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerFillProductData(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest {
	return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AiproductdataenhancerFillProductDataResponse
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerFillProductDataExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataRequest) (*AiproductdataenhancerFillProductDataResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AiproductdataenhancerFillProductDataResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiProductDataEnhancerAPIService.AiProductDataEnhancerFillProductData")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/aiproductdataenhancer.AiProductDataEnhancer/FillProductData"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v RpcStatus
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest struct {
	ctx context.Context
	ApiService AiProductDataEnhancerAPI
	body *AiproductdataenhancerFillProductDataCheckRequest
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest) Body(body AiproductdataenhancerFillProductDataCheckRequest) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest {
	r.body = &body
	return r
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest) Execute() (*AiproductdataenhancerFillProductDataCheckResponse, *http.Response, error) {
	return r.ApiService.AiProductDataEnhancerFillProductDataCheckExecute(r)
}

/*
AiProductDataEnhancerFillProductDataCheck Method for AiProductDataEnhancerFillProductDataCheck

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest
*/
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerFillProductDataCheck(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest {
	return AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AiproductdataenhancerFillProductDataCheckResponse
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerFillProductDataCheckExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerFillProductDataCheckRequest) (*AiproductdataenhancerFillProductDataCheckResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AiproductdataenhancerFillProductDataCheckResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiProductDataEnhancerAPIService.AiProductDataEnhancerFillProductDataCheck")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/aiproductdataenhancer.AiProductDataEnhancer/FillProductDataCheck"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v RpcStatus
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest struct {
	ctx context.Context
	ApiService AiProductDataEnhancerAPI
	body *AiproductdataenhancerTranslateDataRequest
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest) Body(body AiproductdataenhancerTranslateDataRequest) AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest {
	r.body = &body
	return r
}

func (r AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest) Execute() (*AiproductdataenhancerTranslateDataResponse, *http.Response, error) {
	return r.ApiService.AiProductDataEnhancerTranslateDataExecute(r)
}

/*
AiProductDataEnhancerTranslateData Method for AiProductDataEnhancerTranslateData

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest
*/
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerTranslateData(ctx context.Context) AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest {
	return AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return AiproductdataenhancerTranslateDataResponse
func (a *AiProductDataEnhancerAPIService) AiProductDataEnhancerTranslateDataExecute(r AiProductDataEnhancerAPIAiProductDataEnhancerTranslateDataRequest) (*AiproductdataenhancerTranslateDataResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *AiproductdataenhancerTranslateDataResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AiProductDataEnhancerAPIService.AiProductDataEnhancerTranslateData")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/aiproductdataenhancer.AiProductDataEnhancer/TranslateData"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
			var v RpcStatus
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
