/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"encoding/json"
)

// checks if the AiproductdataenhancerFillProductDataCheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiproductdataenhancerFillProductDataCheckRequest{}

// AiproductdataenhancerFillProductDataCheckRequest struct for AiproductdataenhancerFillProductDataCheckRequest
type AiproductdataenhancerFillProductDataCheckRequest struct {
	TenantId             *string `json:"tenantId,omitempty"`
	JobId                *string `json:"jobId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AiproductdataenhancerFillProductDataCheckRequest AiproductdataenhancerFillProductDataCheckRequest

// NewAiproductdataenhancerFillProductDataCheckRequest instantiates a new AiproductdataenhancerFillProductDataCheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiproductdataenhancerFillProductDataCheckRequest() *AiproductdataenhancerFillProductDataCheckRequest {
	this := AiproductdataenhancerFillProductDataCheckRequest{}
	return &this
}

// NewAiproductdataenhancerFillProductDataCheckRequestWithDefaults instantiates a new AiproductdataenhancerFillProductDataCheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiproductdataenhancerFillProductDataCheckRequestWithDefaults() *AiproductdataenhancerFillProductDataCheckRequest {
	this := AiproductdataenhancerFillProductDataCheckRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *AiproductdataenhancerFillProductDataCheckRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerFillProductDataCheckRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *AiproductdataenhancerFillProductDataCheckRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *AiproductdataenhancerFillProductDataCheckRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *AiproductdataenhancerFillProductDataCheckRequest) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerFillProductDataCheckRequest) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *AiproductdataenhancerFillProductDataCheckRequest) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *AiproductdataenhancerFillProductDataCheckRequest) SetJobId(v string) {
	o.JobId = &v
}

func (o AiproductdataenhancerFillProductDataCheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiproductdataenhancerFillProductDataCheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AiproductdataenhancerFillProductDataCheckRequest) UnmarshalJSON(data []byte) (err error) {
	varAiproductdataenhancerFillProductDataCheckRequest := _AiproductdataenhancerFillProductDataCheckRequest{}

	err = json.Unmarshal(data, &varAiproductdataenhancerFillProductDataCheckRequest)

	if err != nil {
		return err
	}

	*o = AiproductdataenhancerFillProductDataCheckRequest(varAiproductdataenhancerFillProductDataCheckRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "jobId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAiproductdataenhancerFillProductDataCheckRequest struct {
	value *AiproductdataenhancerFillProductDataCheckRequest
	isSet bool
}

func (v NullableAiproductdataenhancerFillProductDataCheckRequest) Get() *AiproductdataenhancerFillProductDataCheckRequest {
	return v.value
}

func (v *NullableAiproductdataenhancerFillProductDataCheckRequest) Set(val *AiproductdataenhancerFillProductDataCheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAiproductdataenhancerFillProductDataCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAiproductdataenhancerFillProductDataCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiproductdataenhancerFillProductDataCheckRequest(val *AiproductdataenhancerFillProductDataCheckRequest) *NullableAiproductdataenhancerFillProductDataCheckRequest {
	return &NullableAiproductdataenhancerFillProductDataCheckRequest{value: val, isSet: true}
}

func (v NullableAiproductdataenhancerFillProductDataCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiproductdataenhancerFillProductDataCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
