/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"encoding/json"
)

// checks if the AiproductdataenhancerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiproductdataenhancerError{}

// AiproductdataenhancerError struct for AiproductdataenhancerError
type AiproductdataenhancerError struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewAiproductdataenhancerError instantiates a new AiproductdataenhancerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiproductdataenhancerError() *AiproductdataenhancerError {
	this := AiproductdataenhancerError{}
	return &this
}

// NewAiproductdataenhancerErrorWithDefaults instantiates a new AiproductdataenhancerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiproductdataenhancerErrorWithDefaults() *AiproductdataenhancerError {
	this := AiproductdataenhancerError{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *AiproductdataenhancerError) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerError) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *AiproductdataenhancerError) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *AiproductdataenhancerError) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *AiproductdataenhancerError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *AiproductdataenhancerError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *AiproductdataenhancerError) SetMessage(v string) {
	o.Message = &v
}

func (o AiproductdataenhancerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiproductdataenhancerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableAiproductdataenhancerError struct {
	value *AiproductdataenhancerError
	isSet bool
}

func (v NullableAiproductdataenhancerError) Get() *AiproductdataenhancerError {
	return v.value
}

func (v *NullableAiproductdataenhancerError) Set(val *AiproductdataenhancerError) {
	v.value = val
	v.isSet = true
}

func (v NullableAiproductdataenhancerError) IsSet() bool {
	return v.isSet
}

func (v *NullableAiproductdataenhancerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiproductdataenhancerError(val *AiproductdataenhancerError) *NullableAiproductdataenhancerError {
	return &NullableAiproductdataenhancerError{value: val, isSet: true}
}

func (v NullableAiproductdataenhancerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiproductdataenhancerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


