/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"encoding/json"
)

// checks if the ProductInformationTextInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductInformationTextInfo{}

// ProductInformationTextInfo struct for ProductInformationTextInfo
type ProductInformationTextInfo struct {
	Name                 *string            `json:"name,omitempty"`
	Value                *string            `json:"value,omitempty"`
	Metadata             *map[string]string `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductInformationTextInfo ProductInformationTextInfo

// NewProductInformationTextInfo instantiates a new ProductInformationTextInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductInformationTextInfo() *ProductInformationTextInfo {
	this := ProductInformationTextInfo{}
	return &this
}

// NewProductInformationTextInfoWithDefaults instantiates a new ProductInformationTextInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductInformationTextInfoWithDefaults() *ProductInformationTextInfo {
	this := ProductInformationTextInfo{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProductInformationTextInfo) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInformationTextInfo) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProductInformationTextInfo) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProductInformationTextInfo) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ProductInformationTextInfo) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInformationTextInfo) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ProductInformationTextInfo) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ProductInformationTextInfo) SetValue(v string) {
	o.Value = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ProductInformationTextInfo) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductInformationTextInfo) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ProductInformationTextInfo) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *ProductInformationTextInfo) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

func (o ProductInformationTextInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductInformationTextInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductInformationTextInfo) UnmarshalJSON(data []byte) (err error) {
	varProductInformationTextInfo := _ProductInformationTextInfo{}

	err = json.Unmarshal(data, &varProductInformationTextInfo)

	if err != nil {
		return err
	}

	*o = ProductInformationTextInfo(varProductInformationTextInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "value")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductInformationTextInfo struct {
	value *ProductInformationTextInfo
	isSet bool
}

func (v NullableProductInformationTextInfo) Get() *ProductInformationTextInfo {
	return v.value
}

func (v *NullableProductInformationTextInfo) Set(val *ProductInformationTextInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProductInformationTextInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProductInformationTextInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductInformationTextInfo(val *ProductInformationTextInfo) *NullableProductInformationTextInfo {
	return &NullableProductInformationTextInfo{value: val, isSet: true}
}

func (v NullableProductInformationTextInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductInformationTextInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
