/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"encoding/json"
)

// checks if the GenerateProductDataRequestProductDataToGenerate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateProductDataRequestProductDataToGenerate{}

// GenerateProductDataRequestProductDataToGenerate struct for GenerateProductDataRequestProductDataToGenerate
type GenerateProductDataRequestProductDataToGenerate struct {
	Name     *string  `json:"name,omitempty"`
	ValueSet []string `json:"valueSet,omitempty"`
	// Metadata is an optional field to provide additional information to the AI like, max length, min length, field description, etc.
	Metadata             *map[string]string         `json:"metadata,omitempty"`
	Tone                 *AiproductdataenhancerTone `json:"tone,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GenerateProductDataRequestProductDataToGenerate GenerateProductDataRequestProductDataToGenerate

// NewGenerateProductDataRequestProductDataToGenerate instantiates a new GenerateProductDataRequestProductDataToGenerate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateProductDataRequestProductDataToGenerate() *GenerateProductDataRequestProductDataToGenerate {
	this := GenerateProductDataRequestProductDataToGenerate{}
	return &this
}

// NewGenerateProductDataRequestProductDataToGenerateWithDefaults instantiates a new GenerateProductDataRequestProductDataToGenerate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateProductDataRequestProductDataToGenerateWithDefaults() *GenerateProductDataRequestProductDataToGenerate {
	this := GenerateProductDataRequestProductDataToGenerate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GenerateProductDataRequestProductDataToGenerate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GenerateProductDataRequestProductDataToGenerate) SetName(v string) {
	o.Name = &v
}

// GetValueSet returns the ValueSet field value if set, zero value otherwise.
func (o *GenerateProductDataRequestProductDataToGenerate) GetValueSet() []string {
	if o == nil || IsNil(o.ValueSet) {
		var ret []string
		return ret
	}
	return o.ValueSet
}

// GetValueSetOk returns a tuple with the ValueSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) GetValueSetOk() ([]string, bool) {
	if o == nil || IsNil(o.ValueSet) {
		return nil, false
	}
	return o.ValueSet, true
}

// HasValueSet returns a boolean if a field has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) HasValueSet() bool {
	if o != nil && !IsNil(o.ValueSet) {
		return true
	}

	return false
}

// SetValueSet gets a reference to the given []string and assigns it to the ValueSet field.
func (o *GenerateProductDataRequestProductDataToGenerate) SetValueSet(v []string) {
	o.ValueSet = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GenerateProductDataRequestProductDataToGenerate) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *GenerateProductDataRequestProductDataToGenerate) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetTone returns the Tone field value if set, zero value otherwise.
func (o *GenerateProductDataRequestProductDataToGenerate) GetTone() AiproductdataenhancerTone {
	if o == nil || IsNil(o.Tone) {
		var ret AiproductdataenhancerTone
		return ret
	}
	return *o.Tone
}

// GetToneOk returns a tuple with the Tone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) GetToneOk() (*AiproductdataenhancerTone, bool) {
	if o == nil || IsNil(o.Tone) {
		return nil, false
	}
	return o.Tone, true
}

// HasTone returns a boolean if a field has been set.
func (o *GenerateProductDataRequestProductDataToGenerate) HasTone() bool {
	if o != nil && !IsNil(o.Tone) {
		return true
	}

	return false
}

// SetTone gets a reference to the given AiproductdataenhancerTone and assigns it to the Tone field.
func (o *GenerateProductDataRequestProductDataToGenerate) SetTone(v AiproductdataenhancerTone) {
	o.Tone = &v
}

func (o GenerateProductDataRequestProductDataToGenerate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateProductDataRequestProductDataToGenerate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ValueSet) {
		toSerialize["valueSet"] = o.ValueSet
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Tone) {
		toSerialize["tone"] = o.Tone
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GenerateProductDataRequestProductDataToGenerate) UnmarshalJSON(data []byte) (err error) {
	varGenerateProductDataRequestProductDataToGenerate := _GenerateProductDataRequestProductDataToGenerate{}

	err = json.Unmarshal(data, &varGenerateProductDataRequestProductDataToGenerate)

	if err != nil {
		return err
	}

	*o = GenerateProductDataRequestProductDataToGenerate(varGenerateProductDataRequestProductDataToGenerate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "valueSet")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "tone")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGenerateProductDataRequestProductDataToGenerate struct {
	value *GenerateProductDataRequestProductDataToGenerate
	isSet bool
}

func (v NullableGenerateProductDataRequestProductDataToGenerate) Get() *GenerateProductDataRequestProductDataToGenerate {
	return v.value
}

func (v *NullableGenerateProductDataRequestProductDataToGenerate) Set(val *GenerateProductDataRequestProductDataToGenerate) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateProductDataRequestProductDataToGenerate) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateProductDataRequestProductDataToGenerate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateProductDataRequestProductDataToGenerate(val *GenerateProductDataRequestProductDataToGenerate) *NullableGenerateProductDataRequestProductDataToGenerate {
	return &NullableGenerateProductDataRequestProductDataToGenerate{value: val, isSet: true}
}

func (v NullableGenerateProductDataRequestProductDataToGenerate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateProductDataRequestProductDataToGenerate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
