/*
aiproductdataenhancer/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aiproductdataenhancer

import (
	"encoding/json"
)

// checks if the AiproductdataenhancerGenerateProductDataRequestProductInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiproductdataenhancerGenerateProductDataRequestProductInformation{}

// AiproductdataenhancerGenerateProductDataRequestProductInformation struct for AiproductdataenhancerGenerateProductDataRequestProductInformation
type AiproductdataenhancerGenerateProductDataRequestProductInformation struct {
	TextInfo             *ProductInformationTextInfo  `json:"textInfo,omitempty"`
	ImageInfo            *ProductInformationImageInfo `json:"imageInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AiproductdataenhancerGenerateProductDataRequestProductInformation AiproductdataenhancerGenerateProductDataRequestProductInformation

// NewAiproductdataenhancerGenerateProductDataRequestProductInformation instantiates a new AiproductdataenhancerGenerateProductDataRequestProductInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiproductdataenhancerGenerateProductDataRequestProductInformation() *AiproductdataenhancerGenerateProductDataRequestProductInformation {
	this := AiproductdataenhancerGenerateProductDataRequestProductInformation{}
	return &this
}

// NewAiproductdataenhancerGenerateProductDataRequestProductInformationWithDefaults instantiates a new AiproductdataenhancerGenerateProductDataRequestProductInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiproductdataenhancerGenerateProductDataRequestProductInformationWithDefaults() *AiproductdataenhancerGenerateProductDataRequestProductInformation {
	this := AiproductdataenhancerGenerateProductDataRequestProductInformation{}
	return &this
}

// GetTextInfo returns the TextInfo field value if set, zero value otherwise.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) GetTextInfo() ProductInformationTextInfo {
	if o == nil || IsNil(o.TextInfo) {
		var ret ProductInformationTextInfo
		return ret
	}
	return *o.TextInfo
}

// GetTextInfoOk returns a tuple with the TextInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) GetTextInfoOk() (*ProductInformationTextInfo, bool) {
	if o == nil || IsNil(o.TextInfo) {
		return nil, false
	}
	return o.TextInfo, true
}

// HasTextInfo returns a boolean if a field has been set.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) HasTextInfo() bool {
	if o != nil && !IsNil(o.TextInfo) {
		return true
	}

	return false
}

// SetTextInfo gets a reference to the given ProductInformationTextInfo and assigns it to the TextInfo field.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) SetTextInfo(v ProductInformationTextInfo) {
	o.TextInfo = &v
}

// GetImageInfo returns the ImageInfo field value if set, zero value otherwise.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) GetImageInfo() ProductInformationImageInfo {
	if o == nil || IsNil(o.ImageInfo) {
		var ret ProductInformationImageInfo
		return ret
	}
	return *o.ImageInfo
}

// GetImageInfoOk returns a tuple with the ImageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) GetImageInfoOk() (*ProductInformationImageInfo, bool) {
	if o == nil || IsNil(o.ImageInfo) {
		return nil, false
	}
	return o.ImageInfo, true
}

// HasImageInfo returns a boolean if a field has been set.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) HasImageInfo() bool {
	if o != nil && !IsNil(o.ImageInfo) {
		return true
	}

	return false
}

// SetImageInfo gets a reference to the given ProductInformationImageInfo and assigns it to the ImageInfo field.
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) SetImageInfo(v ProductInformationImageInfo) {
	o.ImageInfo = &v
}

func (o AiproductdataenhancerGenerateProductDataRequestProductInformation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiproductdataenhancerGenerateProductDataRequestProductInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TextInfo) {
		toSerialize["textInfo"] = o.TextInfo
	}
	if !IsNil(o.ImageInfo) {
		toSerialize["imageInfo"] = o.ImageInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) UnmarshalJSON(data []byte) (err error) {
	varAiproductdataenhancerGenerateProductDataRequestProductInformation := _AiproductdataenhancerGenerateProductDataRequestProductInformation{}

	err = json.Unmarshal(data, &varAiproductdataenhancerGenerateProductDataRequestProductInformation)

	if err != nil {
		return err
	}

	*o = AiproductdataenhancerGenerateProductDataRequestProductInformation(varAiproductdataenhancerGenerateProductDataRequestProductInformation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "textInfo")
		delete(additionalProperties, "imageInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *AiproductdataenhancerGenerateProductDataRequestProductInformation) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableAiproductdataenhancerGenerateProductDataRequestProductInformation struct {
	value *AiproductdataenhancerGenerateProductDataRequestProductInformation
	isSet bool
}

func (v NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) Get() *AiproductdataenhancerGenerateProductDataRequestProductInformation {
	return v.value
}

func (v *NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) Set(val *AiproductdataenhancerGenerateProductDataRequestProductInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiproductdataenhancerGenerateProductDataRequestProductInformation(val *AiproductdataenhancerGenerateProductDataRequestProductInformation) *NullableAiproductdataenhancerGenerateProductDataRequestProductInformation {
	return &NullableAiproductdataenhancerGenerateProductDataRequestProductInformation{value: val, isSet: true}
}

func (v NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiproductdataenhancerGenerateProductDataRequestProductInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
